using System;

// ===== Program: Check Whether a Number is Prime =====
// Logic: A prime number is divisible only by 1 and itself

class Program
{
    static void Main()
    {
        Console.Write("Enter a number: ");
        int num = Convert.ToInt32(Console.ReadLine());

        bool isPrime = true;

        if (num <= 1)
        {
            isPrime = false;
        }
        else
        {
            for (int i = 2; i <= num / 2; i++)
            {
                if (num % i == 0)
                {
                    isPrime = false;
                    break;  // stop loop if divisible
                }
            }
        }

        if (isPrime)
            Console.WriteLine(num + " is a Prime Number.");
        else
            Console.WriteLine(num + " is NOT a Prime Number.");
    }
}